/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SocialWall = {
  _id: string;
  _type: "socialWall";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedDate?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = SocialWall | News | Event | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/lib/queries/countdown-queries.ts
// Variable: COUNTDOWN_QUERY
// Query: *[_type == "countdown"] {    title,      eventDate,    }
export type COUNTDOWN_QUERYResult = Array<never>;

// Source: ./src/lib/queries/event-queries.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event"] | order(publishDate desc){        _id,        name,        image{        asset->{        _id,        url}        },        description,    }
export type EVENTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  description: string | null;
}>;

// Source: ./src/lib/queries/faqs-queries.ts
// Variable: FAQs_QUERY
// Query: *[_type == "faqSection"] | order(publishDate desc) {  _id,  title,  faqs[]{    question,    answer  }}
export type FAQs_QUERYResult = Array<never>;

// Source: ./src/lib/queries/news-queries.ts
// Variable: NEWS_ARTICLES_QUERY
// Query: *[_type == "news"] | order(publishDate desc){    _id,    title,    mainImage{    asset->{    _id,    url    }    },      slug,      publishedDate,    }
export type NEWS_ARTICLES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  slug: Slug | null;
  publishedDate: string | null;
}>;
// Variable: SINGLE_NEWS_ARTICLE_QUERY
// Query: *[_type == "news"] | order(publishDate desc){    _id,    body,    title,    mainImage{    asset->{    _id,    url    }    },      slug,      publishedDate,    }
export type SINGLE_NEWS_ARTICLE_QUERYResult = Array<{
  _id: string;
  body: null;
  title: string | null;
  mainImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  slug: Slug | null;
  publishedDate: string | null;
}>;

// Source: ./src/lib/queries/social-wall-queries.ts
// Variable: SOCIAL_WALL_QUERY
// Query: *[_type == "socialWall"]{  images[]{    asset->{      url    }  }}
export type SOCIAL_WALL_QUERYResult = Array<{
  images: Array<{
    asset: {
      url: string | null;
    } | null;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"countdown\"] {\n    title,\n      eventDate,\n    }": COUNTDOWN_QUERYResult;
    "*[_type == \"event\"] | order(publishDate desc){\n        _id,\n        name,\n        image{\n        asset->{\n        _id,\n        url}\n        },\n        description,\n    }": EVENTS_QUERYResult;
    "*[_type == \"faqSection\"] | order(publishDate desc) {\n  _id,\n  title,\n  faqs[]{\n    question,\n    answer\n  }\n}\n\n": FAQs_QUERYResult;
    "*[_type == \"news\"] | order(publishDate desc){\n    _id,\n    title,\n    mainImage{\n    asset->{\n    _id,\n    url\n    }\n    },\n      slug,\n      publishedDate,\n    }": NEWS_ARTICLES_QUERYResult;
    "*[_type == \"news\"] | order(publishDate desc){\n    _id,\n    body,\n    title,\n    mainImage{\n    asset->{\n    _id,\n    url\n    }\n    },\n      slug,\n      publishedDate,\n    }": SINGLE_NEWS_ARTICLE_QUERYResult;
    "*[_type == \"socialWall\"]{\n  images[]{\n    asset->{\n      url\n    }\n  }\n}\n": SOCIAL_WALL_QUERYResult;
  }
}
